export default {
    ORTHOGRAPHIC_CAMERA: 1,
    PERSPECTIVE_CAMERA: 2,

    AMBIENT_LIGHT: 3,
    DIRECTIONAL_LIGHT: 4,

    BASIC_MESH_MATERIAL: 5,
    COMPLEX_MESH_MATERIAL: 6,
    SPRITE_MATERIAL: 7,
    MULTI_SPRITE_MATERIAL: 8,

    MESH: 9,
    SPRITE: 10,
    MULTI_SPRITE: 11,
    OBJECT_3D: 12
};
